name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        template: 
          - aarch64/qemu

    container: 
      image: embox/emdocker:new
      options: --privileged
    
    steps:
    - uses: actions/checkout@v1
    - run: make confload-${{matrix.template}}
    - run: make
    - run: ./scripts/continuous/run.sh ${{matrix.template}}
